name: Publish Docker image

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up jdk
        uses: actions/setup-java@v4
        width:
          java-version: '23'
          distribution: 'temurin'

      - name: build docker image
        run: docker build -t hellodocker .

